# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20161214_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='descripcion',
            field=models.TextField(blank=True, default='', validators=[photos.validators.badwords_detector]),
        ),
    ]
